version: '3'
services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - /Library/PostgreSQL/9.6/data/:/var/lib/postgressql/data/
  chainlink:
    image: "smartcontract/chainlink"
    env_file: .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      - ~/Home/Krieger/chainlink-volume/:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt 