type              = "fluxmonitor"
schemaVersion     = 1
name              = "delta-vault-token-price-job"
contractAddress   = "0x3cCad4715152693fE3BC4460591e3D3Fbd071b42"
externalJobID     = "0EEC7E1D-D0D2-476C-A1A8-72DFB6633F03"

threshold = 0.5
absoluteThreshold = 0.0

idleTimerPeriod   = "1s"
idleTimerDisabled = false

pollTimerPeriod   = "1m"
pollTimerDisabled = false

drumbeatEnabled  = true
drumbeatSchedule = "CRON_TZ=UTC * */20 * * * *"

observationSource = """
    // data source 1 - Coinbase
    ds1 [type="http" method=GET url="https://api.coinbase.com/v2/prices/BTC-USD/spot"]
    ds1_parse [type="jsonparse" path="data,amount"]

    // data source 2 - Binance
    ds2 [type="http" method=GET url="https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT"]
    ds2_parse [type="jsonparse" path="price"]

    // data source 3 - Kraken
    ds3 [type="http" method=GET url="https://api.kraken.com/0/public/Ticker?pair=XBTUSD"]
    ds3_parse [type="jsonparse" path="result,XXBTZUSD,c,0"]

    ds1 -> ds1_parse -> medianized_answer
    ds2 -> ds2_parse -> medianized_answer
    ds3 -> ds3_parse -> medianized_answer

    medianized_answer [type=median]
"""